language: java

install: true

script: ./build/test-spring-compatibility.sh

env:
  - SPRING_VERSION=4.3.2.RELEASE
  - SPRING_VERSION=4.0.7.RELEASE
    SPRING_SECURITY_VERSION=4.0.2.RELEASE
  - SPRING_VERSION=4.2.7.RELEASE
  - SPRING_VERSION=4.1.7.RELEASE
  - SPRING_VERSION=4.0.7.RELEASE
  - SPRING_VERSION=3.2.14.RELEASE

jobs:
  include:
    - stage: test
      script: gradle clean test
    - stage: test
      env: SPRING_VERSION=
