markdown: kramdown
highlighter: rouge
path: https://juhasipo.github.io/juhasipo/multi-user-test-runner.git
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

