version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
  findbugs:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle findbugsMain
  javadoc:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle :core:javadoc
      - persist_to_workspace:
          root: "core/build"
          paths:
            - "docs/javadoc"
  publish_snapshots:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle uploadArchives
workflows:
  version: 2
  release_workflow:
    jobs:
      - build
      - findbugs:
          requires:
            - build
      - javadoc:
          requires:
            - build
      - publish_snapshots:
          type: approval
          requires:
            - findbugs
            - javadoc
