version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: examples/build/test-results
      - store_test_results:
          path: integration-test/build/test-results
      - store_test_results:
          path: java-8-test/build/test-results
      - store_test_results:
          path: junit-5-legacy-test/build/test-results
      - store_test_results:
          path: spring-test/build/test-results
      - store_test_results:
          path: string-test-class-runner/build/test-results
  findbugs:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle findbugsMain
  javadoc:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle :core:javadoc
      - persist_to_workspace:
          root: "core/build"
          paths:
            - "docs/javadoc"
      - store_artifacts:
          path: "core/build/docs/javadoc"
          destination: "javadoc"
  publish_snapshots:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: gradle uploadArchives
workflows:
  version: 2
  release_workflow:
    jobs:
      - build
      - findbugs:
          requires:
            - build
      - javadoc:
          requires:
            - build
      - publish_snapshots:
          type: approval
          requires:
            - findbugs
            - javadoc
