# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle test
  findBugs:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: gradle findbugsMain
  javadoc:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: gradle :core:javadoc
    persist_to_workspace:
      root: javadoc
      paths:
       - core/build/docs/javadoc
   publishSnapshots:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: gradle uploadArchives

workflows:
  version: 2
  release-workflow:
    jobs:
      - build
      - findBugs:
          requires:
            - build
      - javadoc:
          requires:
            - build
      - publishSnapshots:
          requires:
            - findBugs
            - javadoc
